### ISSUE TITLE
Problems connecting to local HAC

### ISSUE THREAD

**Issue by denislutz** [eljoujat/eclipseimpexeditor#17]
Hey El Joujat,

so I tried it again and did some debugging. 

I used this url as configuration,  http://somedomain.local:9001/admin/

For the validate and for the Type Update I get the following exceptions.
I checked the cookie while beeing logged in and it seems ok, it exist under the key you expect in your code. Any idea of what am I doing wrong?

Thanks in advance.

```

!ENTRY impexeditor.core 4 4 2016-02-09 12:06:00.716
!MESSAGE Exception while attemting to refresch data def
!STACK 0
java.lang.IllegalArgumentException: Cookie value must not be null
	at org.jsoup.helper.Validate.notNull(Validate.java:26)
	at org.jsoup.helper.HttpConnection$Base.cookie(HttpConnection.java:295)
	at org.jsoup.helper.HttpConnection.cookie(HttpConnection.java:151)
	at org.eclipseplugins.impexeditor.core.utils.ImpexHttpClient.getCSrfToken(ImpexHttpClient.java:256)
	at org.eclipseplugins.impexeditor.core.utils.ImpexHttpClient.sendLoginPost(ImpexHttpClient.java:131)
	at org.eclipseplugins.impexeditor.core.utils.ImpexHttpClient.getJsessionId(ImpexHttpClient.java:186)
	at org.eclipseplugins.impexeditor.core.utils.ImpexHttpClient.getAllTypes(ImpexHttpClient.java:108)
	at org.eclipseplugins.impexeditor.core.config.ImpexDataDefinition.loadImpexDataDef(ImpexDataDefinition.java:57)
	at org.eclipseplugins.impexeditor.core.config.ImpexDataDefinition.getImpexDataDef(ImpexDataDefinition.java:84)
	at org.eclipseplugins.impexeditor.core.editor.autocompletion.ImpexCompletionProposalComputer.createProposals(ImpexCompletionProposalComputer.java:118)
	at org.eclipseplugins.impexeditor.core.editor.autocompletion.ImpexCompletionProposalComputer.computeCompletionProposals(ImpexCompletionProposalComputer.java:72)
	at org.eclipse.jface.text.contentassist.ContentAssistant$5.run(ContentAssistant.java:1904)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1902)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:573)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:570)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:505)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:499)
	at org.eclipse.jface.text.contentassist.ContentAssistant.showPossibleCompletions(ContentAssistant.java:1720)
	at org.eclipse.jface.text.source.SourceViewer.doOperation(SourceViewer.java:932)
	at org.eclipse.ui.texteditor.ContentAssistAction$1.run(ContentAssistAction.java:82)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.texteditor.ContentAssistAction.run(ContentAssistAction.java:80)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:519)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:122)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1574)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1387)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1412)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1397)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1424)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:824)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3293)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:769)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2098)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:5534)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4668)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9106)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1253)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2477)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3407)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

!ENTRY org.eclipse.ui 4 0 2016-02-09 12:06:09.092
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: Cookie value must not be null
	at org.jsoup.helper.Validate.notNull(Validate.java:26)
	at org.jsoup.helper.HttpConnection$Base.cookie(HttpConnection.java:295)
	at org.jsoup.helper.HttpConnection.cookie(HttpConnection.java:151)
	at org.eclipseplugins.impexeditor.core.utils.ImpexHttpClient.getCSrfToken(ImpexHttpClient.java:256)
	at org.eclipseplugins.impexeditor.core.utils.ImpexHttpClient.sendLoginPost(ImpexHttpClient.java:131)
	at org.eclipseplugins.impexeditor.core.utils.ImpexHttpClient.getJsessionId(ImpexHttpClient.java:186)
	at org.eclipseplugins.impexeditor.core.utils.ImpexHttpClient.validateImpex(ImpexHttpClient.java:239)
	at org.eclipseplugins.impexeditor.core.actions.ValidateImpexAction.run(ValidateImpexAction.java:80)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:253)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4454)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1388)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3799)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3409)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by eljoujat** [comment]
Hi Denis, 
It appears that the we got a null jsessionId, 
the username and password are correct? and the URL used is for the hac (hybris admin console )?

Thanks for your contribution.

**Comment by denislutz** [comment]
Hey ElJoujat,

ok it works, I had a local domain mapping in localhosts and this broke it.

I think it would be helpful if you add more restrictive docu that the url must be exacly as required.

Thanks a lot, the auto complete is really cool. I think this is an advancement in impex development.

**Comment by eljoujat** [comment]
Hi , 

I'm re-opining this issues, because the plugin should also handle domain mapping  as well . 

Thanks

**Comment by denislutz** [comment]
Ok sure, makes sence.

I think you should let the exception bubble up somewhere, otherwise its just kind of swallowed and it delays the debugging process. Since only developers work with it you can show them the underlying issue.

**Comment by eljoujat** [comment]
Hi Denis, 

I was unable to reproduce this issue. 

my hosts file : 
`127.0.1.1  somedomain.local`

I test with a local instance of hybris, the hac is accessible from http://somedomain.local:9001/hac
