### ISSUE TITLE
which hybris version is needed to get the impex editor to work?

### ISSUE THREAD

**Issue by MarkusSchlautmann** [eljoujat/eclipseimpexeditor#24]
we installed the impex editor and configured it according to your documentation.
It looks like, that the login is successful when we start the refresh impex data model process.
Unfortunately we cannot sync the impex data, we are facing the folling error:

Plugin: impexeditor.core
Message: Exception while attemting to refresch data def
Exception Stack Trace
`java.lang.ArrayIndexOutOfBoundsException: 1
	at org.eclipseplugins.impexeditor.core.utils.ImpexHttpClient.sendLoginPost(ImpexHttpClient.java:137)
	at org.eclipseplugins.impexeditor.core.utils.ImpexHttpClient.getJsessionId(ImpexHttpClient.java:156)
	at org.eclipseplugins.impexeditor.core.utils.ImpexHttpClient.getAllTypes(ImpexHttpClient.java:81)
	at org.eclipseplugins.impexeditor.core.config.ImpexDataDefinition.loadImpexDataDef(ImpexDataDefinition.java:57)
	at org.eclipseplugins.impexeditor.core.actions.RefreschDataAction$1.run(RefreschDataAction.java:59)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
`

Session Data:

`eclipse.buildId=4.4.2.M20150204-1700
java.version=1.7.0_75
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product`

Unfortunately we have to use a quite old version of hybris: 4.8.7 and java 1.7
We don't have occ.

Is it possible to use impex editor with this setup?

**Comment by eljoujat** [comment]
Hello , 
the plugin does not need an OCC to run , you just need to configure the host to the right value of your hac access url (hybris administration console) and provide valid username and password .
Let me now if it didn't work .

**Comment by MarkusSchlautmann** [comment]
Hello,

plugin does not work on hybris 4.8.7. I configured access url for hac, username and password.
```
final HttpResponse response = makeHttpPostRequest(hostName + "/console/impex/allTypes", getJsessionId(), Collections.<BasicNameValuePair> emptyList());
final HttpResponse response = makeHttpPostRequest(hostName + "/console/impex/typeAndAttributes", getJsessionId(), params);
```
If i try  /console/impex/allTypes or /console/impex/typeAndAttributes in Firefox i get a 404.
I assume your plugin does not work for hybris version 4.8.7.

Best Regards
