### ISSUE TITLE
While drag-n-drop Eclipse Install button got Unexpected exception while verifying features: 

### ISSUE THREAD

**Issue by paulvi** [eljoujat/eclipseimpexeditor#3]
While drag-n-drop Eclipse Install button 
from 
http://marketplace.eclipse.org/content/hybris-impex-editor
 got Unexpected exception while verifying features: 

<a href="http://marketplace.eclipse.org/marketplace-client-intro?mpc_install=2331084" class="drag" title="Drag to your running Eclipse workspace to install Hybris Impex Editor"><img src="http://marketplace.eclipse.org/sites/all/themes/solstice/_themes/solstice_marketplace/public/images/btn-install.png" alt="Drag to your running Eclipse workspace to install Hybris Impex Editor" /></a>

```
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.standard.product -showlocation
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product -showlocation

org.eclipse.epp.mpc.ui
Error
Mon Jun 15 11:05:39 CST 2015
Unexpected exception while verifying features: 

java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at org.eclipse.epp.internal.mpc.core.util.URLUtil.toURI(URLUtil.java:24)
	at org.eclipse.epp.internal.mpc.ui.operations.AbstractProvisioningOperation.addRepositories(AbstractProvisioningOperation.java:73)
	at org.eclipse.epp.internal.mpc.ui.operations.ResolveFeatureNamesOperation.run(ResolveFeatureNamesOperation.java:46)
	at org.eclipse.epp.internal.mpc.ui.wizards.FeatureSelectionWizardPage$4.run(FeatureSelectionWizardPage.java:304)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by paulvi** [comment]
possibly network related

**Comment by eljoujat** [comment]
I will close as not reproductible 

Thanks
